/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Manga = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
  'chapters' : IDL.Vec(Chapter),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const ReadingHistory = IDL.Record({
  'mangaId' : IDL.Nat,
  'chapterNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [], []),
  'addChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  'addManga' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Manga)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMangaById' : IDL.Func([IDL.Nat], [Manga], ['query']),
  'getMangaList' : IDL.Func([IDL.Nat], [IDL.Vec(Manga)], ['query']),
  'getReadingHistory' : IDL.Func([], [IDL.Vec(ReadingHistory)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordReadingHistory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchManga' : IDL.Func([IDL.Text], [IDL.Vec(Manga)], ['query']),
  'updateManga' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Manga = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
    'chapters' : IDL.Vec(Chapter),
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const ReadingHistory = IDL.Record({
    'mangaId' : IDL.Nat,
    'chapterNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [], []),
    'addChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(ExternalBlob)], [], []),
    'addManga' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Manga)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMangaById' : IDL.Func([IDL.Nat], [Manga], ['query']),
    'getMangaList' : IDL.Func([IDL.Nat], [IDL.Vec(Manga)], ['query']),
    'getReadingHistory' : IDL.Func([], [IDL.Vec(ReadingHistory)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordReadingHistory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchManga' : IDL.Func([IDL.Text], [IDL.Vec(Manga)], ['query']),
    'updateManga' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };